# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c01deaeae1de380d1bd3977da0c4bc7abc6fc6369bcb99ee5fa821dffcb1f948c2c5e3cd47356b3bde02f58e383eaa736d1c0a8b251ba568985138229dd505

test:
  secret_key_base: 85e5ca5cbc289a599b5a1015e38cbd6816bd245cbfa7ed80aa863c03c04fda35d1029f73c412a9a7639f02edcd4fa76ee8fd2dea3e06d72b003a202ad534a0a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
